FROM openjdk:19 AS build

COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN ./mvnw dependency:resolve

COPY src src
RUN ./mvnw package

FROM openjdk:19
WORKDIR devBank
COPY --from=build target/*.jar schoolManagementSystem.jar
ENTRYPOINT ["java", "-jar", "schoolManagementSystem.jar"]